services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    ports:
      - "0.0.0.0:5432:5432"

  nginx:
    build: ./front
    depends_on:
      - app
    ports:
      - 443:443
    restart: always
    volumes:
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro


volumes:
  db:
