services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    ports:
      - "0.0.0.0:5432:5432"

  web:
    build: ./front/.
    ports:
      - "4173:4173"
    depends_on:
      - app

volumes:
  db:
